- AssetRipperConsole/AssetRipperConsole.csproj
- AssetRipperConsole/Program.cs
Hey! I'm using the console app from an automation tool and need more flexibility.
Arguments I've added:
```
-o, --output    Directory to export to. Will be cleared if already exists.
--logFile       (Default: AssetRipperConsole.log) File to log to.
-q, --quit      (Default: false) Close console after export.
--help          Display this help screen.
--version       Display version information.
value pos. 0    Required. Input files or directory to export.
```
> Add command line arguments

- AssetRipperCore/Classes/Texture2D/Texture2D.cs
- AssetRipperCore/Interfaces/IHasImageData.cs
- AssetRipperGUI/AssetInfo/AvaloniaBitmapFromDirectBitmap.cs
- AssetRipperGUI/AssetInfo/SelectedAsset.cs
- AssetRipperGUI/MainWindow.axaml
- AssetRipperLibrary/Exporters/Texture/TextureAssetExporter.cs
- AssetRipperLibrary/Exporters/Texture/TextureConverter.cs
Adds an image viewer tab to the GUI for Texture2D files and an interface to expose images on additional types in future.
> Add image viewer for Texture2D files to gui.

- AssetRipperCore/Classes/Mesh/MeshHelper.cs
- AssetRipperCore/Reading/Classes/MeshHelper.cs
- AssetRipperCore/Structure/GameCollection.cs
- AssetRipperCore/Structure/IFileCollection.cs
- AssetRipperLibrary/Exporters/Textures/TextureExportCollection.cs
Time taken on this stage for Escape from Tarkov reduced from over 15 minutes to 15 seconds.
> Major performance enhancements when "preparing for export"

- AssetRipperCommon/Logging/Logger.cs
- AssetRipperCore/Structure/Assembly/Managers/Il2CppManager.cs
- AssetRipperCore/Structure/GameStructure/GameProcessorContext.cs
- AssetRipperCore/Structure/GameStructure/GameStructure.cs
- AssetRipperCore/Structure/GameStructure/GameStructureProcessor.cs
- AssetRipperCore/Structure/SchemeReader.cs
- AssetRipperGUI/MainWindow.ViewModel.cs
This PR adds support for import status updates to the UI.
It's implemented via an event on the Logger class which can be subscribed to.
A demonstration video can be found [here](https://streamable.com/a1zn83)
> Add status update parameter for UI import progress updates.

- AssetRipperCore/Classes/AnimatorController/Constants/BlendTreeNodeConstant.cs
- AssetRipperCore/Classes/BlendTree/ChildMotion.cs
Just created a method to assign the value. It was being read but not used.
> Fixing 2D Position of BlendTree Childs

- AssetRipperCore/Classes/AudioChorusFilter/AudioChorusFilter.cs
- AssetRipperCore/Classes/AudioDistortionFilter/AudioDistortionFilter.cs
- AssetRipperCore/Classes/AudioEchoFilter/AudioEchoFilter.cs
- AssetRipperCore/Classes/AudioHighPassFilter/AudioHighPassFilter.cs
- AssetRipperCore/Classes/StreamingController/StreamingController.cs
- AssetRipperCore/Parser/Asset/AssetFactory.cs
support for these components 
AudioEchoFilter AudioHighPassFilter AudioChorusFilter AudioDistortionFilter StreamingController
> adds a few more components (mainly audio)

- AssetRipperLibrary/Exporters/Audio/AudioClipDecoder.cs
> Catch errors converting audio

- AssetRipperCommon/Classes/AudioReverbFilter/AudioReverbPreset.cs
- AssetRipperCore/Classes/AudioReverbFilter/AudioReverbFilter.cs
- AssetRipperCore/Parser/Asset/AssetFactory.cs
> Support for AudioReverbFilter

- AssetRipperCore/Classes/SpriteMask/SpriteMask.cs
- AssetRipperCore/Classes/SpriteRenderer/SpriteRenderer.cs
- AssetRipperCore/Parser/Asset/AssetFactory.cs
This pull request implements SpriteMask
> Implement SpriteMask class (and fix minor bug with SpriteRenderer)

- AssetRipperCore/Classes/AudioLowPassFilter/AudioLowPassFilter.cs
- AssetRipperCore/Parser/Asset/AssetFactory.cs
so the reason why i didn't make a pull request for audiolowpass and reverbfilter is becausei was just kinda "lazy"
> AudioLowPassFilter Support

- AssetRipperGUI/MainWindow.ViewModel.cs
- AssetRipperGUI/MainWindow.axaml
Basic Menu Item that shows the current Unity Version, with an option to download it
> Implement #413 [Show Unity Version in GUI]

- AssetRipper.Core/Project/Collections/SceneExportCollection.cs
https://github.com/trouger/AssetRipper/issues/3
> Put scene files in the original path so that SceneManager.LoadScene will work fine

- AssetRipper.Fundamentals/Utils/MathUtils.cs
- AssetRipper.GUI/Components/SpriteExportConfigDropdown.cs
- AssetRipper.Library/Configuration/LibraryConfiguration.cs
- AssetRipper.Library/Configuration/SpriteExportMode.cs
- AssetRipper.Library/Exporters/Textures/ImporterFactory.cs
- AssetRipper.Library/Exporters/Textures/TextureAssetExporter.cs
- AssetRipper.Library/Exporters/Textures/TextureExportCollection.cs
- AssetRipper.Library/Exporters/Textures/YamlSpriteExporter.cs
- AssetRipper.Library/Ripper.cs
- AssetRipper.Tests/MathTests.cs
- Localizations/en_US.json
- Localizations/zh_Hans.json
- Localizations/zh_Hant.json
https://github.com/trouger/AssetRipper/issues/2
> Correct recovery of Sprites

- AssetRipper.Library/AssetRipper.Library.csproj
- AssetRipper.Library/Exporters/Shaders/UnityPatch/YamlShaderPostprocessor.txt
- AssetRipper.Library/Exporters/Shaders/YamlShaderExportCollection.cs
https://github.com/trouger/AssetRipper/issues/9
> Add Shader.Find() support for YAML shader assets

- AssetRipper.Library/AssetRipper.Library.csproj
- AssetRipper.Library/Exporters/Shaders/UnityPatch/YamlShaderPostprocessor.txt
- AssetRipper.Library/Exporters/Shaders/YamlShaderExportCollection.cs
https://github.com/trouger/AssetRipper/issues/9
> Add Shader.Find() support for YAML shaders

- AssetRipper.Library/Exporters/Textures/YamlSpriteExporter.cs
https://github.com/trouger/AssetRipper/issues/11
> Fix yaml sprite pivot

- AssetRipper.GUI/App.axaml
- AssetRipper.GUI/AssetRipper.GUI.csproj
Brings performance enhancements to the asset tree view and NativeAOT support.
> Update to avalonia 11.0 preview 4

- AssetRipper.Core/SourceGenExtensions/AnimationClipExtensions.cs
- AssetRipper.Core/Utils/AnimationCache.cs
- AssetRipper.Library/Processors/AnimationClips/AnimationClipConverter.cs
- AssetRipper.Library/Processors/EditorFormatProcessor.cs
Saved 33% (5 minutes of 15) of the import time on a 30GB game.
> Cache animation clip editor format processor assets

- AssetRipper.Core/Structure/Assembly/Mono/MonoType.cs
- AssetRipper.Core/Structure/Assembly/Serializable/SerializableField.cs
- AssetRipper.SerializationLogic.Tests/FieldSerializationTests.cs
- AssetRipper.SerializationLogic.Tests/GetFieldsInTypeAndBaseTests.cs
- AssetRipper.SerializationLogic/FieldQuery.cs
> Support GenericInstanceType fields

- Localizations/en_US.json
- Source/AssetRipper.Export.UnityProjects/Configuration/LibraryConfiguration.cs
- Source/AssetRipper.Export.UnityProjects/Ripper.cs
- Source/AssetRipper.GUI/MainWindow.ViewModel.Configuration.cs
- Source/AssetRipper.GUI/MainWindow.axaml
i know you said you probably wont even merge this, but i wanted to do it anyway, just cuz it made me feel useful
> IgnoreEngineAssets Button

- Source/AssetRipper.Export.UnityProjects/StreamingAssetsPostExporter.cs
> Copy StreamingAssets Recursively

- Source/AssetRipper.Export.UnityProjects/Textures/ImporterFactory.cs
- Source/AssetRipper.Export.UnityProjects/Textures/TextureConverter.cs
- use the correct NPOTScale
- dont flip cubemaps
resolves #705
> Proper cubemap export

- Source/AssetRipper.GUI/ConsoleApp.cs
> Create logFile directory

- Source/AssetRipper.Assets.Tests/AssetRipper.Assets.Tests.csproj
Reverts AssetRipper/AssetRipper#975
> Revert "Bump Moq from 4.18.4 to 4.20.1"

- Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs
> Fix default state bug on Unity 4

- Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs
> Transition exit time and atomic support on Unity 4

- Source/AssetRipper.GUI.Electron/Pages/Assets/FontTabContent.cshtml
- Source/AssetRipper.GUI.Electron/Pages/Assets/View.cshtml
- Source/AssetRipper.GUI.Electron/Pages/Assets/View.cshtml.cs
In this pull request, I have implemented the font preview feature which enables users to preview fonts https://github.com/AssetRipper/AssetRipper/issues/932
> Implement font preview feature

- Source/AssetRipper.IO.Files/AssetRipper.IO.Files.csproj
- Source/AssetRipper.IO.Files/BundleFiles/FileStream/BundleFileBlockReader.cs
- Source/AssetRipper.IO.Files/BundleFiles/ZstdCompression.cs
Greetings,
Following `PR` should contain a functional implementation of the `Zstd` compression type.
> Implement `Zstd` support

- Source/AssetRipper.GUI.Web/Pages/IndexPage.cs
- Source/AssetRipper.GUI.Web/Pages/Settings/SettingsPage.cs
Updated layout configurations in SettingsPage.cs for better user experience
Settings Page
> Improved Layout in SettingsPage.cs

- Source/AssetRipper.Export.UnityProjects/Audio/AudioClipDecoder.cs
Adds support to export tracker modules. Currently s3m and mod are untested as I've never seen any games utilizing them.
> Tracker Module Support (.it, .xm, .s3m, .mod)

- .github/workflows/docfx_build.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
- nuget.config
This should be the legitimate way of adding the Washi source.
> add nuget.config

- Source/AssetRipper.Import/Structure/Platforms/PlatformGameStructure.cs
Add missing datapack.unity3d asset bundle as a compressed game file
> Include datapack.unity3d asset bundle

- README.md
> fix readme.md not going to the correct license file

- Source/AssetRipper.Export.Modules.Shader/IO/SerializedExtensions.cs
- Source/AssetRipper.Export.Modules.Shader/ShaderBlob/ShaderSubProgram.cs
- Source/AssetRipper.Export.Modules.Shader/ShaderBlob/ShaderSubProgramBlob.cs
- Source/AssetRipper.Export.UnityProjects/Shaders/USCShaderExporter.cs
- Source/AssetRipper.SourceGenerated.Extensions/SerializedPlayerSubProgramExtensions.cs
- Source/AssetRipper.SourceGenerated.Extensions/SerializedProgramExtensions.cs
> 2021.3 Shader Support

- Source/AssetRipper.IO.Files/SerializedFiles/SerializedFile.cs
for the `Write` method in `SerializedFile`:
- add script types
- `objectDataPosition` is aligned to 16 bytes
- each object data is aligned to 8 bytes
Tested by reading and writing back (replacing) a game's `globalgamemanagers.assets` file (the game has unity version `2022.3.6f1`); with these script types and alignments changes, the game won't crash on startup anymore.
> fix alignment and missing script types for writing of `SerializedFile`

- Source/AssetRipper.IO.Files.Tests/FileUtilsTests.cs
- Source/AssetRipper.IO.Files/Utils/FileUtils.cs
> fix file name truncation in presence of non-ascii characters

- docs/articles/Credits.md
- docs/articles/Downloads.md
- docs/articles/Requirements.md
- docs/articles/RoadMap.md
- docs/articles/RunningOnMac.md
- docs/index.md
**before:**
**after:**
**before:**
**after:**
**before:**
**after:**
**before:**
**after:**
**before:**
**after:**
**before:**
**after:**
> Improved article Page Designs

- Source/AssetRipper.Export.Modules.Shader/ShaderBlob/ShaderSubProgramBlob.cs
currentlly if shader blob has multi-segments decompressed blobs would override m_decompressedBlob that only keep last segment's blob,this would trigger exception
> Fix for multi-segment shader blob bugs.

- docs/articles/toc.yml
- Restructured the table of contents to improve organization.
- Added Premium Feature section that was missing.
> [Enhancement]: add Premium Features section and restructure table of contents

- Source/AssetRipper.Export.PrimaryContent/PrimaryContentExporter.cs
- Source/AssetRipper.Export.UnityProjects/ProjectExporter.cs
**Enhance logging with progress indicators for:**
- PrimaryContentExporter
- ProjectExporter
- GameStructure import
> Show Progress in Console while Exporting

- Localizations/en_US.json
- Source/AssetRipper.GUI.SourceGenerator/SettingsPageGenerator.cs
- Source/AssetRipper.GUI.Web/Pages/HtmlExtensions.cs
- Source/AssetRipper.GUI.Web/Pages/Settings/SettingsPage.cs
- Source/AssetRipper.GUI.Web/Pages/Settings/SettingsPage.g.cs
I wanted to change something on the settings page and found this todo: 
> //Todo: add disabled checkbox
So I thought I would implement this to better indicate which settings are for premium users only.
**before:**
**after:**
> Added Disable Checkbox for the Settings Page

- Source/AssetRipper.Processing/AnimationClips/AnimationClipConverter.cs
- Source/AssetRipper.SourceGenerated.Extensions/AnimationCurveExtensions.cs
- Source/AssetRipper.SourceGenerated.Extensions/Vector3CurveExtensions.cs
Get correct Rotation Order for Euler Rotation animation curves in Animation Clips
> AnimationClip's Rotation Order Recovery

- .github/workflows/publish.yml
fixes https://github.com/AssetRipper/AssetRipper/issues/1264, hope i did it right
I have read the CLA Document and I hereby sign the CLA
> Use Ubuntu 22.04 when compiling for Linux

- Localizations/ar.json
- Localizations/en_US.json
- Source/AssetRipper.GUI.Web/Pages/Collections/CollectionAPI.cs
- Source/AssetRipper.GUI.Web/Pages/Collections/ViewPage.cs
- Source/Directory.Build.props
Implements a client-side form that submits Class as a query param. Server applies the filter when rendering the table.
> Add a class filter for the assets
