AssetRipperCore/ClassIDType.cs, AssetRipperCore/Classes/EdgeCollider2D.cs, AssetRipperCore/Classes/EditorSettings/EditorSettings.cs, AssetRipperCore/Classes/GraphicsSettings/GraphicsSettings.cs, AssetRipperCore/Classes/LightmapSettings/LightingSettings.cs, AssetRipperCore/Classes/LightmapSettings/LightmapSettings.cs, AssetRipperCore/Classes/MeshRenderer.cs, AssetRipperCore/Classes/NavMeshData/NavMeshBuildSettings.cs, AssetRipperCore/Classes/ParticleSystemRenderer/ParticleSystemRenderer.cs, AssetRipperCore/Classes/Physics2DSettings/Physics2DSettings.cs, AssetRipperCore/Classes/PhysicsManager/PhysicsManager.cs, AssetRipperCore/Classes/Prefab.cs, AssetRipperCore/Classes/Renderer/Renderer.cs, AssetRipperCore/Classes/Texture2D/Texture2D.cs, AssetRipperCore/Parser/Asset/AssetFactory.cs, AssetRipperCore/Reading/Classes/VideoClip.cs
Fixes reading of Renderer-Derived classes by removing the unneeded 12-byte read.
Fixes MeshRenderer specifically by adding EnlightenVertexStream
More to come.
=> Support for Unity 2020.1 classes

AssetRipperCore/Classes/BuildSettings.cs, AssetRipperCore/Classes/EditorSettings/EditorSettings.cs, AssetRipperCore/Classes/GraphicsSettings/GraphicsSettings.cs, AssetRipperCore/Classes/Light/Light.cs, AssetRipperCore/Classes/MonoManager.cs, AssetRipperCore/Classes/ParticleSystem/CollisionModule/CollisionModule.cs, AssetRipperCore/Classes/ParticleSystem/Trigger/TriggerModule.cs, AssetRipperCore/Classes/Physics2DSettings/Physics2DSettings.cs, AssetRipperCore/Classes/TerrainData/DetailDatabase.cs, AssetRipperCore/Classes/TerrainData/DetailPatch.cs, AssetRipperCore/Classes/TerrainData/DetailPrototype.cs, AssetRipperCore/Classes/TerrainData/TreePrototype.cs, AssetRipperCore/Classes/Texture3D.cs, AssetRipperCore/IO/Extensions/IDictionaryReadAssetExtensions.cs, AssetRipperCore/Project/ProjectExporter.cs, Smolv/SmolvDecoder.cs
Update structs so that unity 2020.2 games can load. 
Exporting currently throws due to a failure with shaders:
```
Error message: Unable to decode SMOL-V shader
Stack trace:    at AssetRipper.Library.Exporters.Shaders.ShaderVulkanExporter.ExportSnippet(TextWriter writer, Stream stream, Int32 offset, Int32 size) in E:\Projects\AssetRipper\AssetRipperLibrary\Exporters\Shaders\ShaderVulkanExporter.cs:line 57
at AssetRipper.Library.Exporters.Shaders.ShaderVulkanExporter.Export(ShaderWriter writer, ShaderSubProgram& subProgram) in E:\Projects\AssetRipper\AssetRipperLibrary\Exporters\Shaders\ShaderVulkanExporter.cs:line 30
at AssetRipper.Core.IO.ShaderWriter.WriteShaderData(ShaderSubProgram& subProgram) in E:\Projects\AssetRipper\AssetRipperCore\IO\ShaderWriter.cs:line 35
at …
```
=> WIP: 2020.2 support

AssetRipperCore/Project/ProjectAssetContainer.cs, AssetRipperCore/YAML/YAMLMappingNode.cs, AssetRipperCore/YAML/YAMLSequenceNode.cs, AssetRipperGUI/AssetInfo/AssetYamlNode.cs, AssetRipperGUI/AssetInfo/SelectedAsset.cs, AssetRipperGUI/AssetRipperGUI.csproj, AssetRipperGUI/MainWindow.ViewModel.cs, AssetRipperGUI/MainWindow.axaml, AssetRipperGUI/MainWindow.axaml.cs, AssetRipperGUI/NewUiFileListing.cs, AssetRipperGUI/UIAssetContainer.cs
Supports viewing (very) basic information about the asset, i.e. its name and type, and also viewing the YAML export tree.
Handles the case where the asset can't be exported as YAML, or throws an exception, so shouldn't crash the GUI.
Explicitly handles and compacts `_typelessdata` fields (large byte arrays) as they cause huge stutters and can't be parsed meaningfully by a human in text form anyway.
=> Add basic asset viewer to GUI

.gitignore, HLSLccWrapper/CMakeLists.txt, HLSLccWrapper/HLSLcc/CMakeLists.txt, Texture2DDecoderNative/CMakeLists.txt, Texture2DDecoderNative/crunch/crn_decomp.h, Texture2DDecoderNative/unitycrunch/crn_decomp.h
Build using:
```bash
cd HLSLccWrapper/HLSLcc/
mkdir build
cd build
cmake ..
cmake --build .
cd ../..
mkdir build
cd build
cmake ..
cmake --build .
cd ../..
cd Texture2DDecoderNative
mkdir build
cd build
cmake ..
cmake --build .
```
Produces files (on linux, untested on mac):
```
HLSLccWrapper/HLSLcc/build/libHLSLcc.so
HLSLccWrapper/build/libHLSLccWrapper.so
Texture2DDecoderNative/build/libTexture2DDecoderNative.so
```
Probably not the most optimal setup but it gives you the so files.
Also added two lines to two parts of the Texture 2D Decoder to allow them to build under non-windows platforms.
=> Add CMakeLists for building native libraries on non-windows platforms

AssetRipperGUI/AssetInfo/SelectedAsset.cs, AssetRipperGUI/MainWindow.axaml
Hide YAML tab for unsupported asset types, show shader data as text.
=> Small GUI Improvements

AssetRipperCore/Structure/Assembly/Mono/MonoUtils.cs, AssetRipperCore/Structure/Assembly/Serializable/SerializableField.cs
Improves detection of which fields are serializable or not. Leads to more MonoBehaviors having parameters correctly restored, and fixes deadlocks with trying to read arrays of several million (or billion!) elements caused by skipping a field prior to the array, leading to the count int being incorrect.
Also includes a warning which is logged if a complex array has a length > 1,000,000, which should help reproduce future crashes. That limit may need raising in the future - but as most of these fields are manually set via the Unity Editor's UI, I find it very unlikely that any game will have an array of more than a million entries.
=> Improvements to detection of serializable fields

AssetRipperCommon/IO/Asset/AssetWriter.cs
Adds a WriteGeneric<T> to AssetWriter to make code generation for AssemblyDumper simpler.
It handles KeyValuePairs, Dictionaries, Arrays, and any combinations of all of those, as well as primitives and IAssetWritables.
=> Add generic write methods to AssetWriter for TypeTreeDumper

AssetRipperCommon/Utils/FileUtils.cs
The for loop inside ran n + n-1 + n-2 + ... + 1 times if there were `n` duplicate files. Not ideal in the case where there were 13k duplicates, for example. (ref #173)
=> Fix FileUtils#GetUniqueFilename being very inefficient

AssetRipperCore/Classes/Mesh/MeshHelper.cs
This PR fixed a possible error in mesh reading, that caused by the use of checked conversion operation from `byte` to `sbyte`.
See https://github.com/ds5678/AssetRipper/blob/fa7f0dbbaf20976a92d211e17f34703dece3b1d6/AssetRipperCore/Classes/Mesh/MeshHelper.cs#L163
Note that `(sbyte)inputBytes[i]` will throw an `OverflowException` when the byte is greater than 127, which i do think is unintended.
<details><summary>exception log</summary>
<p>
```
Message: Error during reading of asset type Mesh
Inner: System.OverflowException: Arithmetic operation resulted in an overflow.
at AssetRipper.Core.Classes.Mesh.MeshHelper.BytesToFloatArray(Byte[] inputBytes, VertexFormat format) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Mesh\MeshHelper.cs:line 142
at …
```
=> Fix `OverflowException` in `MeshHelper.BytesToFloatArray`

AssetRipperCore/Classes/AnimatorController/Constants/BlendTreeNodeConstant.cs
BlendTrees of type Direct don't have 2D Position.
=> Fixing bug in BlendTreeNodeConstant

AssetRipperCore/Classes/ComputeShader/ComputeBufferCounter.cs, AssetRipperCore/Classes/ComputeShader/ComputeShader.cs, AssetRipperCore/Classes/ComputeShader/ComputeShaderBuiltinSampler.cs, AssetRipperCore/Classes/ComputeShader/ComputeShaderCB.cs, AssetRipperCore/Classes/ComputeShader/ComputeShaderKernel.cs, AssetRipperCore/Classes/ComputeShader/ComputeShaderKernelParent.cs, AssetRipperCore/Classes/ComputeShader/ComputeShaderParam.cs, AssetRipperCore/Classes/ComputeShader/ComputeShaderPlatformVariant.cs, AssetRipperCore/Classes/ComputeShader/ComputeShaderResource.cs, AssetRipperCore/Classes/ComputeShader/ComputeShaderVariant.cs, AssetRipperCore/Classes/ComputeShader/EditorOnly/ComputeShaderCompilationContext.cs, AssetRipperCore/Classes/FastPropertyName.cs, AssetRipperCore/Classes/Shader/ShaderError.cs, AssetRipperCore/Parser/Asset/AssetFactory.cs
Should fix export from version 3.4.0 to 2021.2.X
Tested with: Subnautica (2019.2.17f1)
=> Fix for ComputeShader yaml export

AssetRipperCommon/Parser/Asset/DependencyContext.cs, AssetRipperCore/Classes/Shader/Parameters/BufferBinding.cs, AssetRipperCore/Classes/Shader/Parameters/ConstantBuffer.cs, AssetRipperCore/Classes/Shader/Parameters/TextureParameter.cs, AssetRipperCore/Classes/Shader/SerializedShader/SerializedPass.cs, AssetRipperCore/Classes/Shader/SerializedShader/SerializedProgram.cs, AssetRipperCore/Classes/Shader/SerializedShader/SerializedShader.cs, AssetRipperCore/Classes/Shader/SerializedShader/SerializedShaderState.cs, AssetRipperCore/Classes/Shader/SerializedShader/SerializedSubProgram.cs, AssetRipperCore/Classes/Shader/SerializedShader/SerializedSubShader.cs, AssetRipperCore/Classes/Shader/Shader.cs, AssetRipperCore/Classes/Shader/ShaderCompilationInfo.cs, AssetRipperCore/Classes/Shader/ShaderError.cs, AssetRipperLibrary/Exporters/Shaders/YamlShaderExporter.cs
This is a complex feature and will probably not work on every unity version as the yaml layout changed repeatedly through it's history. Furthermore the unity editor doesn't really like shaders as assets and therefor corrupts them from time to time.
=> Make shader exportable as assets

AssetRipperLibrary/Exporters/Textures/TextureExportCollection.cs
This is to discussion as it's a matter of preference and generalization.
In my opinion `SpriteMeshType.FullRect` is the more used option by developers. While Subnautica sprites seems to be fixed with this change I am looking forward with results from other games.
=> Changed SpriteMeshType default value to FullRect

AssetRipper.Fundamentals/Structure/Assembly/Mono/MonoType.cs, AssetRipper.Fundamentals/Structure/Assembly/Serializable/SerializableType.cs
When reading through MonoTypes with fields that (for example) are typed with `List<string>[]`, an argument exception is thrown which breaks asset ripping. This pull request aims to fix it.
**Changes**
- `SerializableType` is rewritten to use array depths, which can be used in the future if Unity adds support for multi-dimensional array types.
- `MonoType` will skip fields if they have an array depth greater than `1`.
- Adds messages to the argument exceptions in `MonoType` so they are more descriptive.
=> Fix Multidimensional Arrays/Lists in Serialization

AssetRipperLibrary/Exporters/Scripts/Assemblies/AssemblyDefinitionAsset.cs, AssetRipperLibrary/Exporters/Scripts/Assemblies/AssemblyDefinitionExporter.cs, AssetRipperLibrary/Exporters/Scripts/ReferenceAssemblies.cs, AssetRipperLibrary/Exporters/Scripts/ScriptExporter.cs
When a game has multiple assemblies, getting compilable scripts often times requires setup from the user for manually creating these assembly definition assets. Furthermore, the user has to setup references to other assemblies, thus requiring extra work.
AssetRipper already knows the assemblies it wants to export, as well as the references those assemblies have to other assemblies, so generating the Assembly Definition Assets seems like another step to remove compiler errors and reduce the setup required once a project is exported.
=> [Enhancement] Export AssemblyDefinition assets

AssetRipperLibrary/Exporters/Scripts/ScriptDecompiler.cs, AssetRipperLibrary/Exporters/Scripts/Transforms/FixEventDeclarationsTransform.cs
Due to the `[CompilerGenerated]` accessor stripping, Event Declarations are invalid.
They export as:
```cs
Modifiers event Type Name
{
add;
remove;
}
```
Which gives compiler error `CS0073: An add or remove accessor must have a body`
This PR fixes it by checking for empty event declarations like these and instead exporting them as bare events:
```cs
Modifiers event Type Name;
```
=> [Enhancement] Fix Exported IL2CPP Event Declarations

AssetRipper.Core/SourceGenExtensions/EditorSettingsExtensions.cs
Cache server upload&download are enabled when a new Unity project is created from Unity Hub.
I think projects exported by AssetRipper should match the default behavior.
=> Enable cache server upload&download

.github/workflows/publish.yml
This PR fixes #551, which is about macOS arm64 binary crashing. For signing the binary I changed the build OS to macOS, and for the bus error I removed the compression flag on arm64. (Seems like arm64 doesn't like compression for now)
And if you don't mind, please add the `hacktoberfest-accepted` label too...
=> fix: macOS arm64 binary crash (fixes #551)

AssetRipper.Core/Structure/GameAssetFactory.cs
When the layout mismatches (too few bytes read), log the name of the script that failed to deserialize, and the difference in expected v actual byte count.
When an exception occurs, log the name of the script that failed.
=> Log extra info about read failures involving MonoBehaviors

AssetRipper.GUI/AssetRipper.GUI.csproj, AssetRipper.Tools.SystemTester/AssetRipper.Tools.SystemTester.csproj
Gives a decent performance boost with basically no downside. Comparison numbers (import times from dropping the folder onto the GUI window, all on the same game on the same PC):
| Configuration              | Time to Editor Format Processing | Time to finish |
--------------------------|--------------------------------------|----------------
| net6 + no server gc        | 3 min 18 sec                     | 5 min 4 sec    |
| net7 + no server gc        | 3 min 10 sec                     | 4 min 55 sec   |
| net7 + server gc           | 2 min 49 sec                     | 4 min 30 sec   |
| net6 + server gc           | 2 min 46 sec                     | 4 min 15 sec   |
=> Enable server garbage collection

AssetRipper.Library/Exporters/Miscellaneous/FontAssetExportCollection.cs
I tried to guess as much as I could, but for some, I had to put sensible defaults such as the force texture case and the ascend calculation mode because I could not find the info on the font. Same deal for some fields like custom characters: I don't know how you get these.
Closes #667
=> Add TrueTypeFontImporter support

Source/AssetRipper.Export.Modules.Shader/UltraShaderConverter/DirectXDisassembler/Blocks/SHDR.cs
Prevents arithmetic overflow issue people have been getting (I think, tested outside of the project).
=> unchecked on SHDR operandData uint cast

Source/AssetRipper.GUI/AssetRipper.GUI.csproj
See https://github.com/AvaloniaUI/Avalonia/issues/6028
This fixes the acrylic issue, where some platforms would not get acrylic.
Because 'av_libglesv2.dll' would not be included with the output.
Specifically in Windows 11 (if not Windows 10).
=> Bump Avalonia to Preview 6

Source/AssetRipper.Processing/AnimationClips/AnimationClipConverter.cs
The conversion with `ToArray` is taking a lot of time, especially since it's repeated often in the loops. The fix is just to initialize the value out of the loops. With this change, I can load my test folder in ~2m, while before I couldn't in 2 hours before.
=> Fix slow down issue in ProcessDenses

Source/AssetRipper.Export.UnityProjects/Textures/ImporterFactory.cs
it turns out that sprites dont like NPOTScale. everything else works with TextureImporterNPOTScale.None, so lets just use that as the default and then only use TextureImporterNPOTScale.ToNearest for cubemaps
cubemap arrays may also need it, but they also may need no FlipY and i currently dont do that, so im just leaving it for now.
=> only use NPOTScale on cubemaps

Source/AssetRipper.Import/AssetRipper.Import.csproj
This version increases the sanity limit on metadata registration count fields, because at least one game in the wild has now exceeded the limits that were in place and therefore was failing to load - this fixes it.
=> Bump Cpp2IL version to build 886

.github/workflows/publish.yml
Based on the guide from the Avalonia docs: https://docs.avaloniaui.net/docs/distribution-publishing/macos
Basically, it just creates the `AssetRipper.app` directory (which is all that .app bundles on MacOS are), copies the release artifacts inside, creates an icon based on the logo, and an `Info.plist` file with the necessary metadata.
This makes AssetRipper a bit nicer to use over having a directory with a bunch of .dlls and also enables me to easily publish it on homebrew (the unofficial MacOS package manager).
=> Bundle Mac release as .app

Source/AssetRipper.Processing/AnimationClips/AnimationClipConverter.cs, Source/AssetRipper.Processing/AnimationClips/CustomCurveResolver.cs
This implements parts of #856 , but done to address the review concerns. Since most of it is unmodified, I left them as co author in the commit.
The main things to mention is most of this is no longer assuming the attributes strings and instead look them up using source generated utilities.
Fixes
Maybe #962 (would need to be tested)
Parts of #954 (the other part is fixed by #973 
An unmentioned part of #853 
cc: @o5zereth
=> Improve the animation attributes string recovery

.github/workflows/publish.yml
And undo creating .app bundles again.
Actually, since we're now just uploading a file, I think it will just upload the zip file as is, so there won't be 2 layers of zipping.
Fixes #985
=> Zip release artifacts before upload to retain executable flag

Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs
- Fixed Mirror, TimeScale and CycleOffset for BlendTree's ChildMotions
- Tweaked BlendTree's default name to replicate the one used in Unity Editor
=> Fixed some properties in BlendTree's ChildMotion

Source/AssetRipper.Export.UnityProjects/Scripts/ScriptDecompiler.cs, Source/AssetRipper.Export.UnityProjects/Scripts/ScriptExportCollection.cs
**Premise:**
When a single script assembly will not decompile the decompilation is left partial: all the assets and code processed prior to that script will be created, however, everything afterwards will not be created or even attempted to decompile.
I ran into this issue when testing the project, a problem-script was causing it to fail, but I could not just recreate it or work around it since everything else was broken as a result.
**Proposed Solution:**
Try/Catch block is used while attempting to decompile the script assembly. This means that the script itself may fail and the error is logged, but we recover and continue to the next assembly. This also allows for future addition of more specific exception catching, in case we want to handle the cases where it is a catastrophic/chain …
=> FIX: Single script decompilation failure causes half-baked result

Source/AssetRipper.Decompilation.CSharp/AssetRipper.Decompilation.CSharp.csproj
Specifying the Washi source in csproj files is no longer necessary due to the nuget.config file added by #1244. This is important because the sources specified in csproj files are forced to be loaded and cannot be avoided even with the `--source` flag in `dotnet build` command etc., in contrary to sources specified in nuget.config file. I should have committed this change in #1244, but I did not notice this problem until I got a build failure lately. Sorry for the complication.
=> remove the washi source in csproj files

Source/AssetRipper.GUI.Web/Pages/Assets/FontTab.cs
https://github.com/AssetRipper/AssetRipper/issues/932 ![image](https://github.com/AssetRipper/AssetRipper/assets/88884784/3a33b0a3-b9cb-4b88-badc-512a7fcbe732)
=> Redo font previewer

Source/AssetRipper.Export.UnityProjects/ExportCollection.cs
=> Fix exported shaders filename bug in Unity 5.5.0+ Resources/AssetBundles

Source/AssetRipper.Processing/AnimationClips/AnimationClipConverter.cs, Source/AssetRipper.Processing/AnimationClips/Editor/StreamedCurveKey.cs, Source/AssetRipper.SourceGenerated.Extensions/AnimationClipExtensions.cs
- only use Negative Infinity slopes on Unity > 2021
- stricter rounding error
- code cleanup
=> AnimationClip Slope Fixes

Source/AssetRipper.Processing/AnimationClips/AnimationClipConverter.cs, Source/AssetRipper.SourceGenerated.Extensions/StreamedClipExtensions.cs
- fixed IStreamedClip.CurveCount() being incorrect for some Unity versions
- fixed GameObject Curves not using the calculated Slopes
=> AnimationClipConverter Fixes

Source/AssetRipper.Export.Modules.Shader/IO/SerializedExtensions.cs
In Disassembly mode, the exported name for the Pass is incorrect because the type is converted to a string directly from an integer, which results in the name being incorrectly displayed as "0". 
**Incorrect Configuration:**
```plaintext
SubShader {
Tags { "CanUseSpriteAtlas" = "true" "IGNOREPROJECTOR" = "true" "PreviewType" = "Plane" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
0 {
Name "Normal"
}
```
**Corrected Configuration:**
```plaintext
SubShader {
Tags { "CanUseSpriteAtlas" = "true" "IGNOREPROJECTOR" = "true" "PreviewType" = "Plane" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
Pass {
Name "Normal"
}
```
=> Fix Incorrect Pass Export Name in Shader Disassembly Mode

Source/AssetRipper.Export.Modules.Shader/IO/SerializedExtensions.cs
1. **Default Value for ColorMask without MRT**: The default value of ColorMask index when MRT is not used is -1, but this does not need to be output. [Just like the above code](https://github.com/AssetRipper/AssetRipper/blob/master/Source/AssetRipper.Export.Modules.Shader/IO/SerializedExtensions.cs#L297), I think the original author forgot to write it.
2. **Inconsistency in Stencil CompareFunction Definitions**: The `CompareFunction` enumeration in the [shader definition](https://docs.unity3d.com/Manual/SL-Stencil.html#comparison-operation-values) is missing the `Disabled` option that is available in [C# definition](https://docs.unity3d.com/ScriptReference/Rendering.CompareFunction.html). This omission leads to compiler errors. In fact, when CompareFunction is set to Disabled, it implies …
=> Fix output error in Disassembly Mode

Source/AssetRipper.Export.Modules.Shader/IO/SerializedExtensions.cs
Sorry for always pulling requests for small issues
I recently used hlslccwrapper to restore the shader in my personal project. I noticed that the clr dll compiled by .net formwork can be read by .net 8 so I modified the hlclcc output to match the unity format.
Therefore, problems are always found intermittently.
I originally thought the issue was due to color and vector being treated as the same value after compilation, which prevented the restoration of the Color definition in the Shader. But when I researched this issue, I realized it was entirely due to the original author's oversight. Color should be directly outputted as Color for it to be recognized in the Material panel.
=> Fix color definition in Shader Properties

Source/AssetRipper.Export.UnityProjects/AssetRipper.Export.UnityProjects.csproj, Source/AssetRipper.Export.UnityProjects/EngineAssets/EngineAssetsFactory.cs, Source/AssetRipper.Export.UnityProjects/EngineAssets/PredefinedAssetCache.cs, Source/AssetRipper.Import/AssetRipper.Import.csproj
This is the AssetRipper portion to add the aabb key in the mesh engine assets
=>  Consider the aabb in the mesh engine assets key

Localizations/en_US.json, Source/AssetRipper.GUI.Web/GameFileLoader.cs, Source/AssetRipper.GUI.Web/Pages/Commands.cs, Source/AssetRipper.GUI.Web/Pages/CommandsPage.cs, Source/AssetRipper.GUI.Web/StaticContent/js/commands_page.js
This PR introduces an option for users to automatically create a timestamped subfolder when exporting assets, preventing accidental overwrites of the selected export directory.
https://github.com/user-attachments/assets/ea4b3b7a-53ef-42f8-8c07-667343e83902
=> Add “Create Subfolder” export option

Source/AssetRipper.Assets/Bundles/Bundle.cs
From my testing on a large project, this reduced the amount of time taken on dependency resolution from 77.870 seconds to 70.741 seconds, about a 10% speedup. This is likely due to lower GC pressure, since closures are no longer being allocated in a tight loop.
=> Use a manual foreach loop instead of LINQ to avoid closure allocation

Localizations/en_US.json, Source/AssetRipper.GUI.Web/Pages/Collections/ViewPage.cs
This adds a dependencies table to collection pages.
The actual problem is when viewing behaviours, there are sometimes references to other assets in the behaviour's serialized fields, and those don't show up in the asset's dependencies tab. I don't know what the design goal around that tab is, so I just added a new table to solve my immediate issue.
=> Add dependencies table to collections view page

Source/AssetRipper.Export.PrimaryContent/Models/GlbModelExporter.cs
See #1510.
A try/catch protection on ExportModel for the error `Can't merge buffer larger than 2gb` was added for #1007. However, commit de7233b removed that try/catch.
This patch simply reinsert the try/catch.
PS: Without deep knowledge of the code, I returned `false` in the catch assuming the common pattern that the bool represent a succesful (or not) export.
=> Reintegrate try/catch removed in de7233b

Source/AssetRipper.SourceGenerated.Extensions/SwitchSwizzle.cs, Source/AssetRipper.SourceGenerated.Extensions/Texture2DExtensions.cs
This pull request implements unswizzling for Nintendo Switch textures. It has been tested on thousands of texture extracted from Fire Emblem Engage successfully
Resolves #629
=> Implement texture unswizzling for Switch platform
